version: '3'

services:
  mysql:
    container_name: roman_iobuilder-poc_mysql
    image: mysql:8
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - "./scripts/user.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/wallet.sql:/docker-entrypoint-initdb.d/2.sql"